config/routes.rb
Rails.application.routes.draw do
  devise_for :user, skip: [:registrations, :passwords], controllers: {
    sessions: 'public/sessions',
  }
  devise_scope :user do
    get 'user/sign_up', to: 'public/registrations#new', as: :new_user_registration
    post 'user', to: 'public/registrations#create', as: :user_registration
    post 'users/guest_sign_in', to: 'public/users/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions',
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'

  get 'search_page' => 'homes#search_page'
  get 'block_page' => 'homes#block_page'
  get 'search' => 'searches#search'

  scope module: :public do
    resources :users, only: [:index, :show, :edit, :update] do
      resources :reports, only: [:new, :create]
      resources :post_requests, only: [:new, :create, :index, :show, :update, :destroy] do
        delete 'reset', on: :collection
      end
      resources :creator_notes do
        delete 'reset', on: :collection
      end
      member do
        get 'potential_followers'
        get 'followings'
        get 'followers'
        get 'bookmarks'
        get 'tweets'
        get 'favorite_tweets'
        patch 'open_request_box'
        patch 'close_request_box'
        patch 'open_creator_notes'
        patch 'close_creator_notes'
      end
    end
    resources :follow_requests, only: [:create, :destroy] do
      delete 'reject', on: :member
    end
    resources :relationships, only: [:create, :destroy] do
      delete 'block', on: :member
    end
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resource :bookmarks, only: [:create, :destroy]
      get 'bookmarking_users', on: :member
    end
    resources :tweets, only: [:index, :show, :create, :destroy] do
      resource :favorites, only: [:create, :destroy]
      get 'favoriting_users', on: :member
    end
  end

  namespace :admin do
    resources :users, only: [:index, :show] do
      resources :reports, only: [:update]
      resources :posts, only: [:index, :show, :destroy] do
      end
      member do
        delete 'destroy_all_posts'
        delete 'destroy_all_tweets'
        delete 'destroy_all_comments'
        delete 'clear_all_reports'
        patch 'block'
        patch 'remove_block'
      end
    end
    resources :offenses, only: [:create, :index, :edit, :update, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarking_users, through: :bookmarks, source: :user, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  def save_tags(savepost_tags)
    # 現在のユーザーの持っているskillを引っ張ってきている
    current_tags = tags.pluck(:name) unless tags.nil?
    # 今postが持っているタグと今回保存されたものの差をすでにあるタグとする。古いタグは消す。
    old_tags = current_tags - savepost_tags
    # 今回保存されたものと現在の差を新しいタグとする。新しいタグは保存
    new_tags = savepost_tags - current_tags

    # Destroy old taggings:
    old_tags.each do |old_name|
      tags.delete Tag.find_by(name: old_name)
    end

    # Create new taggings:
    new_tags.each do |new_name|
      post_tag = Tag.find_or_create_by(name: new_name)
      # 配列に保存
      tags << post_tag
    end
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Post.where(title: content)
    else
      Post.where('title LIKE ?', '%' + content + '%')
    end
  end

  attachment :post_image

  validates :title, presence: true
  validates :body, presence: true

  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  def self.followings_new_posts(user)
    following = user.followings.ids
    Post.where(user_id: following)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(user_id: @user.id).page(params[:page]).per(20)
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find_by(id: params[:id], user_id: @user.id)
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = Post.find_by(id: params[:id], user_id: @user.id)
    if @post.destroy
      redirect_to request.referer, notice: "投稿を削除しました"
    else
      flash.now[:alert] = "投稿を削除できませんでした"
      redirect_to request.referer
    end
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<div class='container'>
   <div class='row'>
    <div class='col-lg-9'>
      <%= link_to "報告一覧", admin_user_path(@user), class: "btn btn-primary my-4" %>
      <h3 class="font-weight-bold">投稿一覧</h3>
      <div class ="d-inline-flex flex-wrap">
        <% @posts.each do |post| %>
          <div class= "px-3 py-3">
            <% if post.post_image.present? %>
              <div>
                <%= link_to admin_user_post_path(@user, post) do %>
                  <%= attachment_image_tag(post, :post_image, :fill, 160, 128) %>
                <% end %>
              </div>
              <p class="font-weight-bold my-2"><%= post.title %></p>
              <%= link_to "削除", admin_user_post_path(@user, post) , method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" %>
            <% else %>
              <div class="d-flex justify-content-center align-items-center" style="width: 160px; height: 128px;">
                <%= link_to admin_user_post_path(@user, post) do %>
                  <h4 class="font-weight-bold"><%= post.title %></h4>
                <% end %>
              </div>
              <p class="my-2">text-only</p>
              <%= link_to "削除", admin_user_post_path(@user, post) , method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class='container'>
   <div class='row'>
    <div class='col-lg-9'>
      <%= link_to "投稿一覧", admin_user_posts_path(@user), class: "btn btn-primary my-4" %>
      <div class="my-4">
        <%= attachment_image_tag(@post, :post_image, :fill, 750, 600) %>
      </div>
      <div class="mx-5 my-4">
        <h3 class="my-4"><%= @post.title %></h3>
     		<h5 class="mb-4">by <%= @user.name %></h5>
        <p class="my-4 lead"><%= @post.body %></p>
        <% @post.tags.each do |tag| %>
          <button class="btn btn-secondary mx-1">#<%= tag.name %></button>
        <% end %>
  		</div>
      <p id="post-<%= @post.id %>-comments-count">コメント件数:<%= @post.comments.count %></p>
      <table id="Comment-List" class="my-5">
        <%= render 'public/comments/comment-list', post: @post %>
      </table>
    </div>
  </div>
</div>