config/routes.rb
Rails.application.routes.draw do
  devise_for :user, skip: [:registrations, :passwords], controllers: {
    sessions: 'public/sessions',
  }
  devise_scope :user do
    get 'user/sign_up', to: 'public/registrations#new', as: :new_user_registration
    post 'user', to: 'public/registrations#create', as: :user_registration
    post 'users/guest_sign_in', to: 'public/users/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions',
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'

  get 'search_page' => 'homes#search_page'
  get 'block_page' => 'homes#block_page'
  get 'search' => 'searches#search'

  scope module: :public do
    resources :users, only: [:index, :show, :edit, :update] do
      resources :reports, only: [:new, :create]
      resources :post_requests, only: [:new, :create, :index, :show, :update, :destroy] do
        delete 'reset', on: :collection
      end
      resources :creator_notes do
        delete 'reset', on: :collection
      end
      member do
        get 'potential_followers'
        get 'followings'
        get 'followers'
        get 'bookmarks'
        get 'tweets'
        get 'favorite_tweets'
        patch 'open_request_box'
        patch 'close_request_box'
        patch 'open_creator_notes'
        patch 'close_creator_notes'
      end
    end
    resources :follow_requests, only: [:create, :destroy] do
      delete 'reject', on: :member
    end
    resources :relationships, only: [:create, :destroy] do
      delete 'block', on: :member
    end
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resource :bookmarks, only: [:create, :destroy]
      get 'bookmarking_users', on: :member
    end
    resources :tweets, only: [:index, :show, :create, :destroy] do
      resource :favorites, only: [:create, :destroy]
      get 'favoriting_users', on: :member
    end
  end

  namespace :admin do
    resources :users, only: [:index, :show] do
      resources :reports, only: [:update]
      resources :posts, only: [:index, :show, :destroy] do
      end
      member do
        delete 'destroy_all_posts'
        delete 'destroy_all_tweets'
        delete 'destroy_all_comments'
        delete 'clear_all_reports'
        patch 'block'
        patch 'remove_block'
      end
    end
    resources :offenses, only: [:create, :index, :edit, :update, :destroy]
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!, only: [:search_page]

  def top
  end

  def search_page
    @posts = Post.followings_new_posts(current_user).order(created_at: :desc).limit(20)
  end

  def block_page
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/block_page.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-9">
      <p>このユーザーは管理者によりログインを制限されています</p>
    </div>
  </div>
</div>

app/views/homes/search_page.html.erb
<div class='container'>
   <div class='row'>

    <div class='col-lg-9'>
      <div class="my-5">
        <div class="my-3">
        <% if user_signed_in? %>
          <%= form_with url: search_path, method: :get, local: true do |f| %>
            <%= f.text_field :content, id: "search-content" ,class: "col-lg-6 mx-3" %>
            <%= f.select :model, options_for_select({ "Post" => "post", "User" => "user", "Tag" => "tag" }) %>
            <%= f.select :method, options_for_select({ "部分一致" => "partial", "完全一致" => "perfect" }) %>
            <%= f.submit '検索', class: "btn btn-sm btn-success" %>
          <% end %>
        <% end %>
        </div>
        <div class="mx-3">
          <%= link_to "新着投稿一覧", posts_path, class: " btn btn-sm btn-secondary" %>
          <%= link_to "ユーザー一覧", users_path, class: "btn btn-sm btn-secondary mx-3" %>
        </div>
      </div>

      <h3 class="my-3 font-weight-bold">フォローユーザーの新着投稿</h3>
      <div class ="d-inline-flex flex-wrap">
        <% @posts.each do |post| %>
          <div class="px-3 py-3">
            <% if post.post_image.present? %>
              <div>
                <%= link_to post_path(post) do %>
                  <%= attachment_image_tag(post, :post_image, :fill, 160, 128) %>
                <% end %>
              </div>
              <p class="font-weight-bold my-2"><%= post.title %></p>
            <% else %>
              <div class="d-flex justify-content-center align-items-center" style="width: 160px; height: 128px;">
                <%= link_to post_path(post) do %>
                  <h5 class="font-weight-bold"><%= post.title %></h5>
                <% end %>
              </div>
              <p class="my-2">text-only</p>
            <% end %>
            <p class="my-2"><%= post.user.name %></p>
          </div>
        <% end %>
      </div>
    </div>
    <div class='col-lg-2 offset-lg-1'>
      <%= render 'public/users/info', user: current_user %>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10">
      <p>ようこそ、Picturescueへ！
        <br>Picturescueはログイン制の画像投稿サイトです。
        <br>ご利用の際は、以下3点のルールを遵守してください。</p>
        <p>①アダルトコンテンツを含んだ画像は投稿しないでください。</p>
        <p>②攻撃的な発言やそれに類する発言をしないでください。</p>
        <p>③自他の個人情報やそれにつながる情報を公開しないでください。</p>
        <p>これ以外の事情であっても、不適切な投稿やツイートは、管理者の判断により、無断で削除されることがあります。
        <br>ルールやマナーを守ってぜひ楽しんでください！</p>
      </p>
    </div>
  </div>
</div>