config/routes.rb
Rails.application.routes.draw do
  devise_for :user, skip: [:registrations, :passwords], controllers: {
    sessions: 'public/sessions',
  }
  devise_scope :user do
    get 'user/sign_up', to: 'public/registrations#new', as: :new_user_registration
    post 'user', to: 'public/registrations#create', as: :user_registration
    post 'users/guest_sign_in', to: 'public/users/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions',
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'

  get 'search_page' => 'homes#search_page'
  get 'block_page' => 'homes#block_page'
  get 'search' => 'searches#search'

  scope module: :public do
    resources :users, only: [:index, :show, :edit, :update] do
      resources :reports, only: [:new, :create]
      resources :post_requests, only: [:new, :create, :index, :show, :update, :destroy] do
        delete 'reset', on: :collection
      end
      resources :creator_notes do
        delete 'reset', on: :collection
      end
      member do
        get 'potential_followers'
        get 'followings'
        get 'followers'
        get 'bookmarks'
        get 'tweets'
        get 'favorite_tweets'
        patch 'open_request_box'
        patch 'close_request_box'
        patch 'open_creator_notes'
        patch 'close_creator_notes'
      end
    end
    resources :follow_requests, only: [:create, :destroy] do
      delete 'reject', on: :member
    end
    resources :relationships, only: [:create, :destroy] do
      delete 'block', on: :member
    end
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resource :bookmarks, only: [:create, :destroy]
      get 'bookmarking_users', on: :member
    end
    resources :tweets, only: [:index, :show, :create, :destroy] do
      resource :favorites, only: [:create, :destroy]
      get 'favoriting_users', on: :member
    end
  end

  namespace :admin do
    resources :users, only: [:index, :show] do
      resources :reports, only: [:update]
      resources :posts, only: [:index, :show, :destroy] do
      end
      member do
        delete 'destroy_all_posts'
        delete 'destroy_all_tweets'
        delete 'destroy_all_comments'
        delete 'clear_all_reports'
        patch 'block'
        patch 'remove_block'
      end
    end
    resources :offenses, only: [:create, :index, :edit, :update, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_posts, through: :bookmarks, source: :post, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_tweets, through: :favorites, source: :tweet, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :tweets, dependent: :destroy

  has_many :post_requests, dependent: :destroy
  has_many :received_requests, class_name: 'PostRequest', foreign_key: 'host_id', dependent: :destroy

  has_many :creator_notes, dependent: :destroy
  has_many :request_notes, class_name: 'PostRequest', foreign_key: 'requester_id', dependent: :destroy

  has_many :reports, dependent: :destroy
  has_many :recieved_reports, class_name: 'Report', foreign_key: 'offender_id', dependent: :destroy

  has_many :follow_requests
  has_many :potential_followings, through: :follow_requests, source: :follow, dependent: :destroy
  has_many :reverse_of_follow_requests, class_name: 'FollowRequest', foreign_key: 'follow_id'
  has_many :potential_followers, through: :reverse_of_follow_requests, source: :user, dependent: :destroy

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow, dependent: :destroy
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user, dependent: :destroy

  attachment :profile_image
  validates :name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.guest
    find_or_create_by!(name: 'guest-user', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guest-user"
    end
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

  def follow_requesting?(other_user)
    potential_followings.include?(other_user)
  end

  def follow_requested_by?(other_user)
    potential_followers.include?(other_user)
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  def followed_by?(other_user)
    followers.include?(other_user)
  end

  def follow_request(other_user)
    unless self == other_user
      follow_requests.find_or_create_by(follow_id: other_user.id)
    end
  end

  def remove_follow_request(other_user)
    follow_request = follow_requests.find_by(follow_id: other_user.id)
    follow_request.destroy if follow_request
  end

  def accept_follow_request(other_user)
    unless self == other_user
      Relationship.find_or_create_by(user_id: other_user.id, follow_id: id)
    end
  end

  def reject_follow_request(other_user)
    follow_request = FollowRequest.find_or_create_by(user_id: other_user.id, follow_id: id)
    follow_request.destroy if follow_request
  end

  def block(other_user)
    relationship = Relationship.find_by(user_id: other_user.id, follow_id: id)
    relationship.destroy if relationship
  end

  def remove(other_user)
    relationship = Relationship.find_by(user_id: id, follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def self.extract_offenders
    reports = Report.all
    offender_ids = []
    reports.each do |report|
      offender_ids.push(report.offender_id)
    end
    User.where(id: offender_ids)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.extract_offenders.page(params[:page]).per(20)
  end

  def show
    @user = User.find(params[:id])
    @reports = @user.recieved_reports.page(params[:page]).per(20)
  end

  def destroy_all_tweets
    @user = User.find(params[:id])
    @tweets = Tweet.where(user_id: @user.id)
    if @tweets.destroy_all
      redirect_to request.referer, notice: "ツイートを全削除しました"
    else
      flash.now[:alert] = "ツイートを削除できませんでした"
      redirect_to request.referer
    end
  end

  def destroy_all_comments
    @user = User.find(params[:id])
    @comments = Comment.where(user_id: @user.id)
    if @comments.destroy_all
      redirect_to request.referer, notice: "コメントを全削除しました"
    else
      flash.now[:alert] = "コメントを削除できませんでした"
      redirect_to request.referer
    end
  end

  def destroy_all_posts
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id)
    if @posts.destroy_all
      redirect_to request.referer, notice: "投稿を全削除しました"
    else
      flash.now[:alert] = "投稿を削除できませんでした"
      redirect_to request.referer
    end
  end

  def clear_all_reports
    @user = User.find(params[:id])
    @reports = Report.where(offender_id: @user.id, is_finished: true)
    if @reports.destroy_all
      redirect_to request.referer, notice: "処理済の報告を削除しました"
    else
      flash.now[:alert] = "処理済の報告を削除できませんでした"
      redirect_to request.referer
    end
  end

  def block
    @user = User.find(params[:id])
    @reports = Report.where(offender_id: @user.id)
    @tweets = Tweet.where(user_id: @user.id)
    @comments = Comment.where(user_id: @user.id)
    @posts = Post.where(user_id: @user.id)
    if @user.update(is_blocked: true)
      @reports.destroy_all
      @tweets.destroy_all
      @comments.destroy_all
      @posts.destroy_all
      redirect_to request.referer, notice: "ユーザーをブロックしました"
    else
      flash.now[:alert] = "ユーザーをブロックできませんでした"
      redirect_to request.referer
    end
  end

  def remove_block
    @user = User.find(params[:id])
    if @user.update(is_blocked: false)
      redirect_to request.referer, notice: "ブロックを解除しました"
    else
      flash.now[:alert] = "ブロックを解除できませんでした"
      redirect_to request.referer
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <h3>報告されたユーザー</h3>
      <table class='table my-4'>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.recieved_reports.count %>件の報告</td>
              <td><%= link_to "Show", admin_user_path(user), class: "btn btn-primary btn-block" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="py-2 pagination-style"><%= paginate @users %></div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <table class='table my-4'>
        <div>
          <%= link_to "ユーザー一覧", admin_users_path, class: "btn btn-primary" %>
          <%= link_to "投稿一覧", admin_user_posts_path(@user), class: "btn btn-success ml-4" %>
          <%= link_to "投稿全削除", destroy_all_posts_admin_user_path(@user), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-danger ml-4" %>
          <%= link_to "ツイート全削除", destroy_all_tweets_admin_user_path(@user), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-danger ml-4" %>
          <%= link_to "コメント全削除", destroy_all_comments_admin_user_path(@user), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-danger ml-4" %>
          <%= link_to "処理済報告リセット", clear_all_reports_admin_user_path(@user), method: :delete, class: "btn btn-warning ml-4" %>
          <% if @user.is_blocked == false %>
            <%= link_to "ブロック", block_admin_user_path(@user), method: :patch, data: { confirm: '本当にブロックしますか？' }, class: "btn btn-secondary ml-4" %>
          <% else %>
            <%= link_to "ブロック解除", remove_block_admin_user_path(@user), method: :patch, data: { confirm: '本当に解除しますか？' }, class: "btn btn-secondary ml-4" %>
          <% end %>
        </div>

        <tbody>
          <% @reports.each do |report| %>
            <tr>
              <td style="width: 10%;">
                <%= attachment_image_tag(report.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %>
                <br><p class="pt-2"><%= report.user.name %></p>
              </td>
              <td style="width: 40%;">
                <% report.offenses.each do |offense| %>
                  <%= offense.name %><br>
                <% end %>
              </td>
              <td style="width: 40%;">
                <%= report.comment %>
              </td>
              <td style="width: 10%;">
                <% if report.is_finished == false %>
                  <%= link_to "未処理",admin_user_report_path(@user, report), method: :patch, data: { confirm: '本当に処理済にしますか？' }, class: "btn btn-secondary" %>
                <% else %>
                  <span class="text-success font-weight-bold">処理済</span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="py-2 pagination-style"><%= paginate @reports %></div>
    </div>
  </div>
</div>