config/routes.rb
Rails.application.routes.draw do
  devise_for :user, skip: [:registrations, :passwords], controllers: {
    sessions: 'public/sessions',
  }
  devise_scope :user do
    get 'user/sign_up', to: 'public/registrations#new', as: :new_user_registration
    post 'user', to: 'public/registrations#create', as: :user_registration
    post 'users/guest_sign_in', to: 'public/users/sessions#guest_sign_in'
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions',
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'

  get 'search_page' => 'homes#search_page'
  get 'block_page' => 'homes#block_page'
  get 'search' => 'searches#search'

  scope module: :public do
    resources :users, only: [:index, :show, :edit, :update] do
      resources :reports, only: [:new, :create]
      resources :post_requests, only: [:new, :create, :index, :show, :update, :destroy] do
        delete 'reset', on: :collection
      end
      resources :creator_notes do
        delete 'reset', on: :collection
      end
      member do
        get 'potential_followers'
        get 'followings'
        get 'followers'
        get 'bookmarks'
        get 'tweets'
        get 'favorite_tweets'
        patch 'open_request_box'
        patch 'close_request_box'
        patch 'open_creator_notes'
        patch 'close_creator_notes'
      end
    end
    resources :follow_requests, only: [:create, :destroy] do
      delete 'reject', on: :member
    end
    resources :relationships, only: [:create, :destroy] do
      delete 'block', on: :member
    end
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resource :bookmarks, only: [:create, :destroy]
      get 'bookmarking_users', on: :member
    end
    resources :tweets, only: [:index, :show, :create, :destroy] do
      resource :favorites, only: [:create, :destroy]
      get 'favoriting_users', on: :member
    end
  end

  namespace :admin do
    resources :users, only: [:index, :show] do
      resources :reports, only: [:update]
      resources :posts, only: [:index, :show, :destroy] do
      end
      member do
        delete 'destroy_all_posts'
        delete 'destroy_all_tweets'
        delete 'destroy_all_comments'
        delete 'clear_all_reports'
        patch 'block'
        patch 'remove_block'
      end
    end
    resources :offenses, only: [:create, :index, :edit, :update, :destroy]
  end
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class='bg-dark'>
  <div class='container'>
    <div class='row'>
      <div class='mx-auto'>
        <p>フッター</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <div class="col-2">
        <a class="navbar-brand" href="/">
          <div>Picturescue</div>
        </a>
      </div>
      <div class="col-10">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
              <li><%= link_to '会員一覧', admin_users_path, class: "btn btn-light mx-2" %></li>
              <li><%= link_to '報告タグ一覧', admin_offenses_path, class: "btn btn-light mx-2" %></li>
              <li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "btn btn-light mx-2" %></li>
            <% elsif user_signed_in? %>
              <li><%= link_to '新規投稿', new_post_path, class: "btn btn-light mx-2" %></li>
              <li><%= link_to '検索ページ', search_page_path, class: "btn btn-light mx-2" %></li>
              <li><%= link_to 'SNS', tweets_path, class: "btn btn-light mx-2" %></li>
              <li><%= link_to 'マイページ', user_path(current_user), class: "btn btn-light mx-2" %></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-light mx-2" %></li>
            <% else %>
              <li><%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post, class: "btn btn-light mx-2" %></li>
              <li><%= link_to '新規登録', new_user_registration_path, class: "btn btn-light mx-2" %></li>
              <li><%= link_to 'ログイン', new_user_session_path, class: "btn btn-light mx-2" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Picturescue</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <p class="text-success"><%= notice %></p>
      <p class="text-danger"><%= alert %></p>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>